In [1]:
import numpy as np
import pandas as pd

In [2]:
data_info = pd.read_csv("../30s_segment_description.csv")

In [15]:
size = np.array([np.array(s.split("x")).astype(int) for s in data_info["size"][:200]])

In [17]:
np.mean(size, axis=0)

array([848.285, 437.32 ])

In [19]:
np.min(size, axis=0)

array([794, 354])

In [21]:
np.max(size, axis=0)

array([853, 480])